services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: offerzonline_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@postgres_db:5432/offerzonline
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:16-alpine
    container_name: offerzonline_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: offerzonline
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
